project:
  type: website
  output-dir: _site

website:
  title: "Tutoring – Dr Ian Henry"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Contact
        href: contact.qmd
    right:
      - text: Main Hub
        href: https://drianhenry.co.uk

format:
  html:
    theme: cosmo
    css: 
      - _theme/_base.scss
      - _theme/colors.scss

