project:
  type: website
  output-dir: _site
  resources:
    - images

website:
  title: "Tutoring – Dr Ian Henry"
  site-url: "https://tutoring.drianhenry.co.uk"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Contact
        href: contact.qmd
    right:
      - text: Main Hub
        href: https://drianhenry.co.uk

format:
  html:
    theme: cosmo
    toc: false
    sitemap: true
    title-block-style: none
    page-layout: full
    css: 
      - _theme/_base.css
      - _theme/_colors.css
    include-in-header: 
      - _includes/_structured-data-tutoring.html
      - _includes/_ga4.html
    include-after-body: 
      - _includes/_footer.html
      - _includes/_cookie-consent.html
